server:
  port: 9393
management:
  contextPath: /management
  security:
    enabled: false
info:
  app:
    name: "@project.artifactId@"
    description: "@project.name@"
    version: "@project.version@"
security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: ${security.oauth2.client.clientId:false} # myclientid
      client-secret: ${security.oauth2.client.clientSecret:} # mysecret
      access-token-uri: ${security.oauth2.client.accessTokenUri:} # http://127.0.0.1:9999/oauth/token
      user-authorization-uri: ${security.oauth2.client.userAuthorizationUri:} # http://127.0.0.1:9999/oauth/authorize
    resource:
      user-info-uri: ${security.oauth2.resource.userInfoUri:} # http://127.0.0.1:9999/me
spring:
  application:
    name: dataflow
  cloud:
    config:
      uri: http://localhost:8888
    deployer:
      cloudfoundry:
        task:
          apiTimeout: 360
        stream:
          apiTimeout: 360
    dataflow:
      security:
        cf-use-uaa: false

#
# If you prefer to use Eureka to locate the Config Server, you can do that by setting
# spring.cloud.config.discovery.enabled=true (default "false"). The net result of that is 
# that client apps all need a bootstrap.yml (or an environment variable) with the Eureka 
# server address, e.g. in eureka.client.serviceUrl.defaultZone
#
#  cloud:
#     config:
#        discovery:
#           enabled: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
