server:
  port: 9393
management:
  contextPath: /management

info:
  app:
    name: "@project.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

security:
  basic:
    enabled: false
#  oauth2:
#    client:
#      client-id: myclient
#      client-secret: mysecret
#      access-token-uri: http://127.0.0.1:9999/oauth/token
#      user-authorization-uri: http://127.0.0.1:9999/oauth/authorize
#    resource:
#      user-info-uri: http://127.0.0.1:9999/me

spring:
  application:
    name: dataflow
  cloud:
    config:
      uri: http://localhost:8888
    dataflow:
      features:
        tasksEnabled: false
    deployer:
      cloudfoundry:
        taskTimeout: 360

#
# If you prefer to use Eureka to locate the Config Server, you can do that by setting
# spring.cloud.config.discovery.enabled=true (default "false"). The net result of that is 
# that client apps all need a bootstrap.yml (or an environment variable) with the Eureka 
# server address, e.g. in eureka.client.serviceUrl.defaultZone
#
#  cloud:
#     config:
#        discovery:
#           enabled: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
